## Qualifier Codes Over Time

```{r 'analysis_qualifierCodes', echo = FALSE}
imgFiles <- file.path("..", imgPath, c("analysis_qualifierCodes_arrestQualifiers.pdf",
                                       "analysis_qualifierCodes_courtQualifiers.pdf",
                                       "analysis_qualifierCodes_histogram.pdf"))
txtFile <- file.path("..", txtPath, "analysis_qualifierCodes_topCodes.txt")
if (any(!file.exists(imgFiles)) || !file.exists(txtFile)) {
  addTables <- function(t1, t2) {
    names <- sort(union(names(t1), names(t2)))
    counts <- integer(length(names))
    base::names(counts) <- names; rm(names)
    
    counts[match(names(t1), names(counts))] <- unname(t1)
    counts[match(names(t2), names(counts))] <- counts[match(names(t2), names(counts))] + unname(t2)
    
    structure(counts, dim = length(counts), dimnames = list(names(counts)), class = "table")
  }

  loadData("qualifierCodes", "..")
  loadData(mainTable, "..")
  years <- sort(unique(obts$court_event_year))
  
  ## arrest qualifiers
  usageByYear <- lapply(years, function(year) {
    yearRows <- obts$court_event_year == year
    codeTable <- table(substring(obts$arrest_qualifier[yearRows], 1L, 2L))
    for (i in seq.int(2L, 7L)) {
      codeTable <- addTables(codeTable, table(substring(obts$arrest_qualifier[yearRows], 2L * i - 1L, 2L * i)))
    }
    codeTable
  })
  
  allCodes <- names(usageByYear[[1L]])
  for (i in seq.int(2L, length(years))) allCodes <- union(allCodes, names(usageByYear[[i]]))
  
  arrestCodeTable <- matrix(0L, length(allCodes), length(years), dimnames = list(allCodes, NULL))
  for (i in seq_along(years))
    arrestCodeTable[match(names(usageByYear[[i]]), allCodes),i] <- usageByYear[[i]]
  rm(usageByYear, allCodes)
  
  arrestCodeTable <- arrestCodeTable[rownames(arrestCodeTable) != "  ",]
  arrestCodeTable <- arrestCodeTable[order(rowSums(arrestCodeTable), decreasing = TRUE),]
  
  
  totalCounts <- sort(rowSums(arrestCodeTable))
  countOrder <- order(rowSums(arrestCodeTable))
  
  cutoffs <- c(100000L, 10000L, 1000L, 100L, 10L, 1L)
  indexSets <- list()
  indexSets[[1L]] <- countOrder[unname(totalCounts > cutoffs[1L])]
  for (i in seq.int(2L, length(cutoffs))) indexSets[[i]] <- countOrder[unname(totalCounts <= cutoffs[i - 1L] & totalCounts > cutoffs[i])]
  rm(cutoffs, totalCounts, countOrder)
  
  pdf(imgFiles[1L], 6, 7.76)
  par(mfrow = getGridDim(8.5 / 11, length(indexSets)), mar = c(2.2, 2.2, 0.1, 2.0))
  
  for (i in seq_along(indexSets)) {
    indices <- indexSets[[i]]
    plot(NULL, type = "n", xlim = range(years), ylim = c(0, max(arrestCodeTable[indices,])),
         xlab = "year", ylab = "count", xaxs = "i")
    plotColors <- rep_len(seq_len(8L), length(indices))
    plotLineTypes <- rep.int(seq_len(8L), length(indices) %/% 8L + if (length(indices) %% 8L != 0L) 1L else 0L)[seq_len(length(indices))]
    for (j in seq_along(indices)) 
      lines(years, arrestCodeTable[indices[j],], col = plotColors[j], lty = plotLineTypes[j])
    mtext(rownames(arrestCodeTable)[indices], side = 4, line = 0.5, at = arrestCodeTable[indices,length(years)],
          cex = 0.6, las = 2, col = plotColors)
  }
  dev.off()
  rm(plotLineTypes, plotColors, indices, indexSets)
  
  ## court qualifiers
  usageByYear <- lapply(years, function(year) {
    yearRows <- obts$court_event_year == year
    codeTable <- table(substring(obts$court_qualifier[yearRows], 1L, 2L))
    for (i in seq.int(2L, 7L)) {
      codeTable <- addTables(codeTable, table(substring(obts$court_qualifier[yearRows], 2L * i - 1L, 2L * i)))
    }
    codeTable
  })
  
  allCodes <- names(usageByYear[[1L]])
  for (i in seq.int(2L, length(years))) allCodes <- union(allCodes, names(usageByYear[[i]]))
  
  courtCodeTable <- matrix(0L, length(allCodes), length(years), dimnames = list(allCodes, NULL))
  for (i in seq_along(years))
    courtCodeTable[match(names(usageByYear[[i]]), allCodes),i] <- usageByYear[[i]]
  rm(usageByYear, allCodes)
  
  courtCodeTable <- courtCodeTable[rownames(courtCodeTable) != "  ",]
  courtCodeTable <- courtCodeTable[order(rowSums(courtCodeTable), decreasing = TRUE),]
  
  
  totalCounts <- sort(rowSums(courtCodeTable))
  countOrder <- order(rowSums(courtCodeTable))
  
  cutoffs <- c(39000L, 10000L, 1000L, 100L, 10L, 1L)
  indexSets <- list()
  indexSets[[1L]] <- countOrder[unname(totalCounts > cutoffs[1L])]
  for (i in seq.int(2L, length(cutoffs))) indexSets[[i]] <- countOrder[unname(totalCounts <= cutoffs[i - 1L] & totalCounts > cutoffs[i])]
  rm(cutoffs, totalCounts, countOrder)
  
  pdf(imgFiles[2L], 6, 7.76)
  par(mfrow = getGridDim(8.5 / 11, length(indexSets)), mar = c(2.2, 2.2, 0.1, 2.0))
  
  for (i in seq_along(indexSets)) {
    indices <- indexSets[[i]]
    plot(NULL, type = "n", xlim = range(years), ylim = c(0, max(courtCodeTable[indices,])),
         xlab = "year", ylab = "count", xaxs = "i")
    plotColors <- rep_len(seq_len(8L), length(indices))
    plotLineTypes <- rep.int(seq_len(8L), length(indices) %/% 8L + if (length(indices) %% 8L != 0L) 1L else 0L)[seq_len(length(indices))]
    for (j in seq_along(indices)) 
      lines(years, courtCodeTable[indices[j],], col = plotColors[j], lty = plotLineTypes[j])
    mtext(rownames(courtCodeTable)[indices], side = 4, line = 0.5, at = courtCodeTable[indices,length(years)],
          cex = 0.6, las = 2, col = plotColors)
  }
  dev.off()
  rm(plotLineTypes, plotColors, indices, indexSets)
  
  rm(i, j, years, addTables)
  
  pdf(imgFiles[3L], 4.5, 3)
  par(mfrow = c(1L, 2L))
  hist(rowSums(arrestCodeTable), breaks = 20, main = "Histogram Arrest QC Count",
       xlab = "total count", freq = TRUE)
  hist(rowSums(courtCodeTable), breaks = 20, main = "Histogram Court QC Count",
       xlab = "total count", freq = TRUE)
  dev.off()
  
  uapply <- function(x, f) f(x)
  arrestCodeTable <- uapply(rowSums(arrestCodeTable), function(x) x[x > 500L])
  courtCodeTable <- uapply(rowSums(courtCodeTable), function(x) x[x > 500L])
  rm(uapply)
  
  topCodes <- union(names(arrestCodeTable), names(courtCodeTable))
  topCodesTable <- data.frame(qualifier = topCodes, arrest_count = 0L, court_count = 0L)
  topCodesTable[match(names(arrestCodeTable), topCodes), "arrest_count"] <- unname(arrestCodeTable)
  topCodesTable[match(names(courtCodeTable), topCodes), "court_count"] <- unname(courtCodeTable)
  topCodesTable <- topCodesTable[order(topCodesTable$arrest_count + topCodesTable$court_count, decreasing = TRUE),]
  
  qualifierCodeRows <- match(topCodesTable$qualifier, qualifierCodes$qualifier)
  topCodesTable$literal_short <- qualifierCodes$literal_short[qualifierCodeRows]
  topCodesTable$type <- qualifierCodes$code_type[qualifierCodeRows]
  topCodesTable$literal <- qualifierCodes$literal_long[qualifierCodeRows]
  
  topCodesTable <- rmdFormat(topCodesTable, maxRows = NA)
  
  writeLines(topCodesTable,
             txtFile)
  
  rm(arrestCodeTable, courtCodeTable, qualifierCodeRows, topCodes)
} else {
  topCodesTable <- readLines(txtFile)
}
rm(imgFiles, txtFile)
```

This section shows the usage of qualifier codes over time. The vast majority of codes are used $< 10$ times overall, while a few have usages in the thousands. The following histograms show the frequencies of total occurences, that is the codes are tabulated across all records and what is displayed is how many have those counts.

`r rmdImageInline(file.path(imgPath, "analysis_qualifierCodes_histogram.pdf"))`

Codes with 500 or more usages in the arrest or court section are show in the table below. When a value is given as `NA`, it does not exist in the qualifier codes section of the OBTS Tech Manual.

`r paste0(topCodesTable, collapse = "\n")`

Finally, we show the usage of codes over time.

`r rmdPageBreak()`

#### Arrest Qualifiers

`r rmdImageInline(file.path(imgPath, "analysis_qualifierCodes_arrestQualifiers.pdf"))`

`r rmdPageBreak()`

#### Court Qualifiers

`r rmdImageInline(file.path(imgPath, "analysis_qualifierCodes_courtQualifiers.pdf"))`