---
title: "__DATANAME_U__ Data Inventory"
output:
  pdf_document:
    includes:
      in_header: ../common/src/styles.sty
    keep_tex: true
  html_document: default
---

```{r 'setup', include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

## This file is written from the assumption that it sits in a folder structure such as:
## root \
##   - common \
##     - data
##   - projectName \
##     file.Rmd
##
## and will look for a target file in ../common/data, which is to be shared by all projects

datasetName <- "__DATANAME_U__"
datasetDir  <- "__DATANAME__"

srcPath <- file.path("src")

## defines a bunch of path variables, loadData(), stuff like that
source(file.path(srcPath, "setup.R"), local = TRUE)
```

```{r 'run_clean', echo = FALSE, include = FALSE, results = "hide"}
## if the clean rmd file exists, this runs just the source in it
## technically, it constructs the output twice, but all the computations
## are cached
cleanRmdFile <- file.path(datasetDir, "clean.Rmd")
if (file.exists(cleanRmdFile)) {
  sourceFile <- file.path(datasetDir, "clean.R")
  knitr::purl(file.path(datasetDir, "clean.Rmd"), sourceFile)
  setwd(datasetDir)
  source("clean.R")
  unlink("clean.R")
  setwd("..")
}
rm(cleanRmdFile, sourceFile)
```

```{r 'abstract_include', child = if (file.exists(abstractFile <- file.path(datasetDir, "abstract.Rmd"))) abstractFile else NULL }
```

# Introduction

```{r 'tables_summary', echo = FALSE, results = "asis"}
for (i in seq_len(nrow(tables))) {
  if (tables$display[i] == 0) next
  
  cat("### ", tables$display_name[i], "\n\n", sep = "")
  if (tables$description[i] != "")
    cat(tables$description[i], "\n\n", sep = "")
  
  firstFive <- formatFirstFiveRows(tables$name[i])
  if (length(firstFive) != 1L || firstFive != "")
    cat("#### Sample Rows\n\n", paste0(firstFive, collapse = "\n"), "\n", sep = "")
  
  variablesSummary <- summarizeVariables(tables$name[i])
  if (length(variablesSummary) != 1L || variablesSummary != "")
    cat("#### Variable Summary\n\n", paste0(rmdFormat(variablesSummary, maxRows = NA), collapse = "\n"), "\n\n", sep = "")
}
rm(i, firstFive, variablesSummary)
```

`r rmdPageBreak()`

# Tables

## Main Table Variables

```{r main_table_variables, echo=FALSE, results="asis"}
variables <- read.csv(file.path(datasetDir, paste0(mainTable, "_variables.csv")),
                      stringsAsFactors = FALSE)
pageBreak <- rmdPageBreak()
firstVariable <- TRUE
for (i in seq_len(nrow(variables))) {
  variable <- variables[i,]
  if (is.numeric(variable[["skip"]]) && variable[["skip"]] == 1L) next
  
  if (!firstVariable) cat(pageBreak)
  else firstVariable <- FALSE
  
  cat("### ", variable[["name"]], "\n\n", sep = "")
  
  if (is.character(variable[["description"]]) && !is.na(variable[["description"]]) && variable[["description"]] != "")
    cat("#### Description\n\n", variable[["description"]], "\n\n", sep = "")
  if (is.character(variable[["value_labels"]]) && !is.na(variable[["value_labels"]]) && variable[["value_labels"]] != "")
    cat("#### Labels\n\n", variable[["value_labels"]], "\n\n", sep = "")
  if (is.character(variable[["question_text"]]) && !is.na(variable[["question_text"]]) && variable[["question_text"]] != "")
    cat("#### Prompt\n\n", variable[["question_text"]], "\n\n", sep = "")
  if (is.character(variable[["notes"]]) && !is.na(variable[["notes"]]) && variable[["notes"]] != "")
    cat("#### Notes\n\n", variable[["notes"]], "\n\n", sep = "")
  
  if (is.numeric(variable[["contains_pii"]]) && !is.na(variable[["contains_pii"]]) && variable[["contains_pii"]] == 1L)
    next
  
  variableSummary <- summarizeVariable(variable[["name"]])
  if (length(variableSummary) != 1L || variableSummary != "") {
    cat("#### Summary\n\n")
    cat(variableSummary, sep = "\n")
    cat("\n")
  }
}
rm(i, pageBreak, firstVariable, variable, variableSummary)
```

```{r 'recommendations_include', child = if (file.exists(recommendationsFile <- file.path(datasetDir, "recommendations.Rmd"))) recommendationsFile else NULL }
```

```{r 'clean_include', child = if (file.exists(cleanFile <- file.path(datasetDir, "clean.Rmd"))) cleanFile else NULL }
```

```{r 'analysis_include', echo = FALSE, results = 'asis'}
analysisFiles <- list.files(datasetDir, "analysis_")
if (length(analysisFiles) > 0L) {
  analysisDir <- file.path(normalizePath(getwd()), datasetDir)
  
  for (i in seq_along(analysisFiles)) {
    if (i > 1L) cat(rmdPageBreak())
    cat(knitr::knit_child(file.path(analysisDir, analysisFiles[i]), options = list(root.dir = analysisDir), quiet = TRUE), "\n\n", sep = "")
  }
  
  rm(i, analysisDir)
}
rm(analysisFiles)
```